[package]
name = "bridgestan"
version = "1.0.2"
edition = "2021"

[dependencies]
libloading = "0.8.0"
once_cell = "1.17.1"
thiserror = "1.0.40"

[build-dependencies]
bindgen = "0.65.1"

[dev-dependencies]
approx = "0.5.1"
