[bridgestan]
git-tree-sha1 = "247b321809bb1a1ddd011f69648ae729ba8282c4"
lazy = true

    [[bridgestan.download]]
    sha256 = "8bd57926e2afb694d2d246a08efb1ab6b56027adcdbeb6ab0407ed58aba88778"
    url = "https://github.com/roualdes/bridgestan/releases/download/v2.0.0/bridgestan-2.0.0.tar.gz"
